import { filterStateI } from '../types/common';

export const filterScheme: filterStateI = {
  name: undefined,
  minCost: undefined,
  maxCost: undefined,
  category: undefined,
  filter: undefined,
};

interface CountryCode {
  code: string;
  country: string;
}

export const countryCodes: CountryCode[] = [
  { code: '+61', country: 'Австралия' },
  { code: '+43', country: 'Австрия' },
  { code: '+994', country: 'Азербайджан' },
  { code: '+355', country: 'Албания' },
  { code: '+213', country: 'Алжир' },
  { code: '+244', country: 'Ангола' },
  { code: '+376', country: 'Андорра' },
  { code: '+1', country: 'Антигуа и Барбуда' },
  { code: '+54', country: 'Аргентина' },
  { code: '+374', country: 'Армения' },
  { code: '+93', country: 'Афганистан' },
  { code: '+1', country: 'Багамы' },
  { code: '+880', country: 'Бангладеш' },
  { code: '+1', country: 'Барбадос' },
  { code: '+973', country: 'Бахрейн' },
  { code: '+375', country: 'Беларусь' },
  { code: '+501', country: 'Белиз' },
  { code: '+32', country: 'Бельгия' },
  { code: '+229', country: 'Бенин' },
  { code: '+359', country: 'Болгария' },
  { code: '+591', country: 'Боливия' },
  { code: '+387', country: 'Босния и Герцеговина' },
  { code: '+267', country: 'Ботсвана' },
  { code: '+55', country: 'Бразилия' },
  { code: '+673', country: 'Бруней' },
  { code: '+226', country: 'Буркина-Фасо' },
  { code: '+257', country: 'Бурунди' },
  { code: '+975', country: 'Бутан' },
  { code: '+379', country: 'Ватикан' },
  { code: '+44', country: 'Великобритания' },
  { code: '+36', country: 'Венгрия' },
  { code: '+58', country: 'Венесуэла' },
  { code: '+670', country: 'Восточный Тимор' },
  { code: '+84', country: 'Вьетнам' },
  { code: '+241', country: 'Габон' },
  { code: '+509', country: 'Гаити' },
  { code: '+592', country: 'Гайана' },
  { code: '+220', country: 'Гамбия' },
  { code: '+233', country: 'Гана' },
  { code: '+502', country: 'Гватемала' },
  { code: '+224', country: 'Гвинея' },
  { code: '+245', country: 'Гвинея-Бисау' },
  { code: '+49', country: 'Германия' },
  { code: '+504', country: 'Гондурас' },
  { code: '+1', country: 'Гренада' },
  { code: '+30', country: 'Греция' },
  { code: '+995', country: 'Грузия' },
  { code: '+45', country: 'Дания' },
  { code: '+253', country: 'Джибути' },
  { code: '+1', country: 'Доминика' },
  { code: '+1', country: 'Доминиканская Республика' },
  { code: '+20', country: 'Египет' },
  { code: '+260', country: 'Замбия' },
  { code: '+263', country: 'Зимбабве' },
  { code: '+972', country: 'Израиль' },
  { code: '+91', country: 'Индия' },
  { code: '+62', country: 'Индонезия' },
  { code: '+962', country: 'Иордания' },
  { code: '+964', country: 'Ирак' },
  { code: '+98', country: 'Иран' },
  { code: '+353', country: 'Ирландия' },
  { code: '+354', country: 'Исландия' },
  { code: '+34', country: 'Испания' },
  { code: '+39', country: 'Италия' },
  { code: '+967', country: 'Йемен' },
  { code: '+238', country: 'Кабо-Верде' },
  { code: '+7', country: 'Казахстан' },
  { code: '+855', country: 'Камбоджа' },
  { code: '+237', country: 'Камерун' },
  { code: '+1', country: 'Канада' },
  { code: '+974', country: 'Катар' },
  { code: '+254', country: 'Кения' },
  { code: '+357', country: 'Кипр' },
  { code: '+686', country: 'Кирибати' },
  { code: '+86', country: 'Китай' },
  { code: '+57', country: 'Колумбия' },
  { code: '+269', country: 'Коморы' },
  { code: '+242', country: 'Конго' },
  { code: '+506', country: 'Коста-Рика' },
  { code: '+53', country: 'Куба' },
  { code: '+965', country: 'Кувейт' },
  { code: '+996', country: 'Кыргызстан' },
  { code: '+856', country: 'Лаос' },
  { code: '+371', country: 'Латвия' },
  { code: '+266', country: 'Лесото' },
  { code: '+231', country: 'Либерия' },
  { code: '+218', country: 'Ливия' },
  { code: '+961', country: 'Ливан' },
  { code: '+423', country: 'Лихтенштейн' },
  { code: '+370', country: 'Литва' },
  { code: '+352', country: 'Люксембург' },
  { code: '+230', country: 'Маврикий' },
  { code: '+222', country: 'Мавритания' },
  { code: '+261', country: 'Мадагаскар' },
  { code: '+389', country: 'Македония' },
  { code: '+265', country: 'Малави' },
  { code: '+60', country: 'Малайзия' },
  { code: '+223', country: 'Мали' },
  { code: '+960', country: 'Мальдивы' },
  { code: '+356', country: 'Мальта' },
  { code: '+212', country: 'Марокко' },
  { code: '+692', country: 'Маршалловы Острова' },
  { code: '+52', country: 'Мексика' },
  { code: '+691', country: 'Микронезия' },
  { code: '+373', country: 'Молдова' },
  { code: '+377', country: 'Монако' },
  { code: '+976', country: 'Монголия' },
  { code: '+258', country: 'Мозамбик' },
  { code: '+95', country: 'Мьянма' },
  { code: '+264', country: 'Намибия' },
  { code: '+674', country: 'Науру' },
  { code: '+977', country: 'Непал' },
  { code: '+227', country: 'Нигер' },
  { code: '+234', country: 'Нигерия' },
  { code: '+31', country: 'Нидерланды' },
  { code: '+505', country: 'Никарагуа' },
  { code: '+64', country: 'Новая Зеландия' },
  { code: '+47', country: 'Норвегия' },
  { code: '+971', country: 'ОАЭ' },
  { code: '+968', country: 'Оман' },
  { code: '+92', country: 'Пакистан' },
  { code: '+680', country: 'Палау' },
  { code: '+507', country: 'Панама' },
  { code: '+675', country: 'Папуа-Новая Гвинея' },
  { code: '+595', country: 'Парагвай' },
  { code: '+51', country: 'Перу' },
  { code: '+48', country: 'Польша' },
  { code: '+351', country: 'Португалия' },
  { code: '+7', country: 'Россия' },
  { code: '+40', country: 'Румыния' },
  { code: '+250', country: 'Руанда' },
  { code: '+503', country: 'Сальвадор' },
  { code: '+685', country: 'Самоа' },
  { code: '+378', country: 'Сан-Марино' },
  { code: '+239', country: 'Сан-Томе и Принсипи' },
  { code: '+966', country: 'Саудовская Аравия' },
  { code: '+268', country: 'Свазиленд' },
  { code: '+1', country: 'Сент-Винсент и Гренадины' },
  { code: '+1', country: 'Сент-Китс и Невис' },
  { code: '+1', country: 'Сент-Люсия' },
  { code: '+381', country: 'Сербия' },
  { code: '+248', country: 'Сейшелы' },
  { code: '+65', country: 'Сингапур' },
  { code: '+963', country: 'Сирия' },
  { code: '+421', country: 'Словакия' },
  { code: '+386', country: 'Словения' },
  { code: '+677', country: 'Соломоновы Острова' },
  { code: '+252', country: 'Сомали' },
  { code: '+249', country: 'Судан' },
  { code: '+597', country: 'Суринам' },
  { code: '+1', country: 'США' },
  { code: '+232', country: 'Сьерра-Леоне' },
  { code: '+992', country: 'Таджикистан' },
  { code: '+886', country: 'Тайвань' },
  { code: '+66', country: 'Таиланд' },
  { code: '+255', country: 'Танзания' },
  { code: '+228', country: 'Того' },
  { code: '+676', country: 'Тонга' },
  { code: '+1', country: 'Тринидад и Тобаго' },
  { code: '+216', country: 'Тунис' },
  { code: '+993', country: 'Туркменистан' },
  { code: '+90', country: 'Турция' },
  { code: '+688', country: 'Тувалу' },
  { code: '+256', country: 'Уганда' },
  { code: '+998', country: 'Узбекистан' },
  { code: '+380', country: 'Украина' },
  { code: '+598', country: 'Уругвай' },
  { code: '+63', country: 'Филиппины' },
  { code: '+358', country: 'Финляндия' },
  { code: '+33', country: 'Франция' },
  { code: '+385', country: 'Хорватия' },
  { code: '+236', country: 'ЦАР' },
  { code: '+235', country: 'Чад' },
  { code: '+382', country: 'Черногория' },
  { code: '+420', country: 'Чехия' },
  { code: '+56', country: 'Чили' },
  { code: '+41', country: 'Швейцария' },
  { code: '+46', country: 'Швеция' },
  { code: '+94', country: 'Шри-Ланка' },
  { code: '+593', country: 'Эквадор' },
  { code: '+240', country: 'Экваториальная Гвинея' },
  { code: '+291', country: 'Эритрея' },
  { code: '+372', country: 'Эстония' },
  { code: '+251', country: 'Эфиопия' },
  { code: '+27', country: 'ЮАР' },
  { code: '+82', country: 'Южная Корея' },
  { code: '+1', country: 'Ямайка' },
  { code: '+81', country: 'Япония' },
];
